name: Deploy to Maven Repository

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up
        uses: ./.github/workflows/actions/setup
        with:
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish to GitHub Packages Apache Maven
        run: mvn --batch-mode --update-snapshots deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_DEPLOY_TOKEN }}
