name: Test with Maven

on:
  push:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/actions/setup/action.yml
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
