name: Test with Maven

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/setup
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
